services:
  db:
    container_name: alloydb
    image: google/alloydbomni
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - alloydb_volume:/var/lib/postgresql/data
    networks:
      - instances_network

  service:
    container_name: service
    build:
      context: ./service
      dockerfile: Dockerfile
    command: >
      sh -c "gunicorn wsgi:app -b 0.0.0.0:8000"
    volumes:
      - ./service:/app
    depends_on:
      db:
        condition: service_started
    ports:
      - "8000:8000"
    networks:
      - gateway_network
      - instances_network

  gateway:
    container_name: gateway
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - gateway_network

networks:
  gateway_network:
    driver: bridge
  instances_network:
    driver: bridge

volumes:
  alloydb_volume:
